name: FW16 QMK Firmware ISO Keyboard

on:
  push:
    branches: [master,main]
    paths: ['fw16_iso/**']


env:
  KEYMAP: hexa
  KEYBOARD: framework/iso 
  TAG: v0.2.9

jobs:
  Build-QMK-Firmware-Keyboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          path: keymaps
      - name: Checkout QMK repo
        uses: actions/checkout@v4
        with:
          repository: FrameworkComputer/qmk_firmware
          submodules: recursive
          path: qmk_firmware
          ref: $TAG
      - name: Copy iso keyboard file into QMK Firmware
        run: cp -r "./keymaps/fw16_iso"  "./qmk_firmware/keyboards/framework/iso/keymaps/${KEYMAP}"
      - name: Copy userspace files into QMK Firmware
        run: cp -r "./keymaps/hexa" "./qmk_firmware/users/hexa"
      - name: Build Firmware
        run: util/docker_build.sh $KEYBOARD:$KEYMAP
        working-directory: ./qmk_firmware 
      - name: Get directory
        run: ls     
      - name: Get directory qmk
        run: ls
        working-directory: ./qmk_firmware
      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexa-firmware-fw16-keyboard
          path: ./qmk_firmware/framework_iso_hexa.uf2
          if-no-files-found: error