name: FW16 QMK Firmware Macropad

on:
  push:
    branches: [master,main]
    paths: ['fw16_macropad/**']


env:
  KEYMAP: hexa
  KEYBOARD: framework/macropad

jobs:
  Build-QMK-Firmware-Macropad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          path: keymaps
      - name: Get latest release with tag
        id: latestrelease
        run: echo "::set-output name=releasetag::$(curl -s https://github.com/FrameworkComputer/qmk_firmware/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: Confirm release tag
        run: echo ${{ steps.latestrelease.outputs.releasetag }}
      - name: Checkout QMK repo
        uses: actions/checkout@v4
        with:
          repository: FrameworkComputer/qmk_firmware
          submodules: recursive
          path: qmk_firmware
          ref: ${{ steps.latestrelease.outputs.releasetag }}
      - name: Copy macropad files into QMK Firmware
        run: cp -r "./keymaps/fw16_macropad"  "./qmk_firmware/keyboards/framework/macropad/keymaps/${KEYMAP}"
      - name: Copy userspace files into QMK Firmware
        run: cp -r "./keymaps/hexa" "./qmk_firmware/users/hexa"
      - name: /Build Firmware
        run: utildocker_build.sh $KEYBOARD:$KEYMAP
        working-directory: ./qmk_firmware 
      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexa-firmware-fw16-macropad
          path: ./qmk_firmware/framework_macropad_hexa.uf2
          if-no-files-found: error